apiVersion: apps/v1
kind: Deployment
metadata:
  name: maison-lumiere-deployment
  labels:
    app: maison-lumiere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maison-lumiere
  template:
    metadata:
      labels:
        app: maison-lumiere
    spec:
      containers:
      - name: maison-lumiere-container
        image: pedro26042005/maison-lumiere:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: maison-lumiere-service
spec:
  type: NodePort
  selector:
    app: maison-lumiere
  ports:
    - protocol: TCP
      port: 80        # porta interna do cluster
      targetPort: 80  # porta do container
      nodePort: 30080 # porta externa que você acessa via IP do nó
